Changes to 'Building Java Cloud Applications with Micronaut and OCI' workshop
oracle/learning-library pull request #1838
Opened 2020-09-02 16:54 UTC by kamryn-v

1. Added screenshots
2. Corrected typos

2020-09-03 08:13 UTC, graemerocher requested changes
hi @kamryn-v thanks for the PR. Some changes seem to modify code snippets, was this intentional?

2020-09-03 08:13 UTC, graemerocher commented on developer-library/micronaut-oci-atp/helidon/helidon.md
> -```
Why were these lines deleted?

2020-09-03 08:13 UTC, graemerocher commented on developer-library/micronaut-oci-atp/helidon/helidon.md
> +- `curl -i http://localhost:8080/health` - returns health status (MicroProfile health format)
Why was this port changed?

2020-09-03 08:13 UTC, graemerocher commented on developer-library/micronaut-oci-atp/deploy/deploy.md
> +    bash
I think the word `bash` can just be removed for all these snippets

2020-09-03 13:48 UTC, graemerocher commented
@kamryn-v could you alter to include only your changes?

2020-09-03 15:53 UTC, kamryn-v commented
Yes, I am pushing the changes to Github to my personal account now.

On Thu, Sep 3, 2020 at 9:48 AM Graeme Rocher <notifications@github.com>
wrote:

> @kamryn-v <https://github.com/kamryn-v> could you alter to include only
> your changes?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/oracle/learning-library/pull/1838#issuecomment-686504565>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQNL2HXZEZWAHXPUZL3ABULSD6NDFANCNFSM4QTKW75Q>
> .
>

2020-09-03 17:27 UTC, kaymalcolm reviewed
Looks good Kamryn!  I made a few edits.  @graemerocher are you good with this iteration?

2020-09-03 17:42 UTC, graemerocher commented
Yes looks good

2020-09-04 14:20 UTC, kaymalcolm approved these changes

2020-09-04 14:20 UTC, merged