ODI & EDQ workshop edits
oracle/learning-library pull request #2383
Opened 2020-12-14 15:50 UTC by NarayananRamakrishnan

2020-12-14 16:42 UTC, kaymalcolm requested changes
This workshop needs to be in a different location.

2020-12-15 16:47 UTC, NarayananRamakrishnan commented
EDQ Updates - created a new folder "data-quality" and move the EDQ workshop into the folder

2020-12-16 20:35 UTC, tmcginn approved these changes
Rene Fontcha will make any corrections required for this PR

2020-12-17 13:24 UTC, kaymalcolm approved these changes

2020-12-17 13:24 UTC, merged