Archiving APEX 20.2 HOLs
oracle/learning-library pull request #3033
Opened 2021-05-04 13:56 UTC by shlayel

Creating an archive folder for APEX 20.2.
The current active HOLs will still be in the same place and needs to get updated once 21.1 is released.

2021-05-04 14:21 UTC, kaymalcolm requested changes
Hey Salim.  Not requesting any changes.  Checking to see if these changes impact any of the links for the workshops that are currently in production now.  I didn't see any workshop IDs so assuming this is all the apex workshops?  Just don't want to break any that are live.

2021-05-04 14:24 UTC, shlayel commented
Hi Kay,

Yes. They are all APEX workshops. Nothing will get impacted.
This is just a copy folder. The exiting labs still function as intended.

Regards,
Salim

From: Kay Malcolm ***@***.***>
Sent: Tuesday, May 4, 2021 6:22 PM
To: oracle/learning-library ***@***.***>
Cc: Salim Hlayel ***@***.***>; Author ***@***.***>
Subject: [External] : Re: [oracle/learning-library] Archiving APEX 20.2 HOLs (#3033)


@kaymalcolm requested changes on this pull request.

Hey Salim. Not requesting any changes. Checking to see if these changes impact any of the links for the workshops that are currently in production now. I didn't see any workshop IDs so assuming this is all the apex workshops? Just don't want to break any that are live.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/oracle/learning-library/pull/3033*pullrequestreview-651296315__;Iw!!GqivPVa7Brio!OwE-dYy9TUaAhdXTFHJjtc7Vb5qsq9F2phzmMHYSNDY4IyWvku9DzjY_Yj00o-xlcw$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/AQMWWT4C7YSUWD5ZF25BMCDTL77I7ANCNFSM44CYNDQA__;!!GqivPVa7Brio!OwE-dYy9TUaAhdXTFHJjtc7Vb5qsq9F2phzmMHYSNDY4IyWvku9DzjY_Yj1At7LuoA$>.

2021-05-05 17:56 UTC, davidastart approved these changes
I talked to Kay and she approves.

2021-05-05 17:57 UTC, davidastart approved these changes

2021-05-05 17:58 UTC, merged