pt_BR first batch
oracle/learning-library pull request #3037
Opened 2021-05-04 16:31 UTC by andreambrosiooracle

two INTRO files from the first livelab

2021-05-05 17:09 UTC, davidastart requested changes
The workshop ID must be included with all pull requests.

2021-05-05 18:38 UTC, andreambrosiooracle commented
Thanks for letting me know, David! How can I fix it?

André Ambrósio | Cloud Solutions Specialist | ***@***.***

From: davidastart ***@***.***>
Sent: quarta-feira, 5 de maio de 2021 14:10
To: oracle/learning-library ***@***.***>
Cc: Andre Ambrosio ***@***.***>; Author ***@***.***>
Subject: [External] : Re: [oracle/learning-library] pt_BR first batch (#3037)


@davidastart requested changes on this pull request.

The workshop ID must be included with all pull requests.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/oracle/learning-library/pull/3037*pullrequestreview-652553567__;Iw!!GqivPVa7Brio!LB2JmS-yIqgc6oNEyVF9QcQGTuMXk6rVU7DezC_wmbyD_bNMgIhlGAigNLdo3l_pgkY$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/AM7MENGY75GHMO2AJ5IHR7LTMF3W7ANCNFSM44DBI5GQ__;!!GqivPVa7Brio!LB2JmS-yIqgc6oNEyVF9QcQGTuMXk6rVU7DezC_wmbyD_bNMgIhlGAigNLdoANhPeCY$>.

2021-05-05 20:27 UTC, davidastart commented
If you log into the LWMS, LiveLabs Workshop Management System you can get the ID of your workshop. Each pull request needs to be tied to a workshop.

2021-05-10 17:57 UTC, kamryn-v approved these changes

2021-05-10 18:25 UTC, merged