Update setup.md
oracle/learning-library pull request #3047
Opened 2021-05-04 22:12 UTC by RichardExley

Minor Fixes based on feedback

2021-05-05 17:08 UTC, davidastart requested changes
The workshop ID must be included with all pull requests.

2021-05-06 12:13 UTC, RichardExley commented
workshop_id=637

2021-05-10 15:56 UTC, tmcginn approved these changes

2021-05-10 16:11 UTC, oegentil approved these changes

2021-05-11 22:55 UTC, RichardExley commented
> The workshop ID must be included with all pull requests.



> The workshop ID must be included with all pull requests.

workshop_id=637

2021-05-12 04:55 UTC, davidastart approved these changes

2021-05-12 04:59 UTC, merged