optional step added
oracle/learning-library pull request #3107
Opened 2021-05-17 08:38 UTC by bilegt-bat-ochir

LWMS 4882, modified prerequisites lab, changed a step to optional status.

2021-05-18 20:08 UTC, kamryn-v requested changes
Hi @bilegt-bat-ochir, can you include the LWMS ID for this workshop?

2021-05-19 07:04 UTC, bilegt-bat-ochir commented
Hi Katryn, LWMS id was in the description. LWMS 4882, modified prerequisites lab, changed a step to optional status.

2021-05-20 06:03 UTC, bilegt-bat-ochir commented
> Hi @bilegt-bat-ochir, can you include the LWMS ID for this workshop?

Hi @kamryn-v Changes are committed, and LWMS ID is 4882, thank you :)

2021-05-20 13:16 UTC, kamryn-v approved these changes

2021-05-20 13:16 UTC, merged