WMS ID # 3120 : Migrate WebLogic Server to OCI with Autonomous Database updates
oracle/learning-library pull request #3203
Opened 2021-06-15 07:41 UTC by nujehowlett

@streamnsight Outstanding updates identified by OHC Learn Publishing Team

2021-06-15 12:23 UTC, tmcginn reviewed
@streamnsight - are you ok with these changes?

2021-06-16 15:58 UTC, streamnsight requested changes
@nujehowlett 
A few minor comments for your review. 
Thanks

2021-06-16 15:58 UTC, streamnsight commented on developer-library/weblogic-to-oci/migrate-app-db-atp-datapump/migrate-app-db-atp-datapump.md
> +    Make sure to specify the proper domain name (here `nonjrf_domain`) if you didn't follow the naming convention of this workshop.
I would keep the emphasis here as it is important.

2021-06-17 07:25 UTC, nujehowlett commented on developer-library/weblogic-to-oci/intro-oci/intro-oci.md
> +* A private or public SSH key-pair.
@streamnsight I have updated as requested.

2021-06-17 07:25 UTC, nujehowlett commented on developer-library/weblogic-to-oci/migrate-app-db-atp-datapump/migrate-app-db-atp-datapump.md
> +    Make sure to specify the proper domain name (here `nonjrf_domain`) if you didn't follow the naming convention of this workshop.
@streamnsight I have updated as requested.

2021-06-21 12:53 UTC, tmcginn approved these changes

2021-06-21 12:53 UTC, merged