Workshop #7401 - Updated the manfest.json files.
oracle/learning-library pull request #3711
Opened 2021-09-09 14:38 UTC by SuRajan

updated the manifest.json files in freetier and livelabs folders.
Workshop #7401

2021-09-09 14:50 UTC, rfontcha commented on data-management-library/oracle-machine-learning/oml-fun-on-ADB/omlserv/omlserv.md
> -# Title of the Lab
@SuRajan - Please remove changes to this file from your request. It's not part of WMS ID 7041

2021-09-09 14:51 UTC, rfontcha requested changes
@SuRajan - View comment about unrelated file to be removed from your PR

2021-09-09 14:54 UTC, rfontcha requested changes
@SuRajan - Actually this entire PR has nothing to do with 7041. Please rename the title accordingly with the correct WMS ID. If the workshop is not yet in WMS, then withdraw your pull request and first submit the workshop entry to WMS

2021-09-10 16:18 UTC, SuRajan commented
@rfontcha This PR is for workshop #7401(OML Fundamentals on ADB). Are you perhaps confusing this with #7041?
Please let me know.

2021-09-10 16:22 UTC, rfontcha approved these changes
@SuRajan Thanks for pointing that out. My mistake, very easy to confuse as they look alike 7401 vs 7041!

2021-09-10 20:38 UTC, anooshapilli approved these changes

2021-09-10 20:38 UTC, merged