Self QA started
oracle/learning-library pull request #3746
Opened 2021-09-14 20:40 UTC by Kuassim

Self QA started- Updates as of Sept 14th

2021-09-15 00:29 UTC, rfontcha requested changes
@Kuassim  The numbering scheme/hierarchy calls for:

1. - # (H1 - Title and only one per MD)
2. - ## (H2 - Task n..)
3. - 1., 2., 3., ....n.
4. - -/* (bullet) - as many levels as needed


Please convert anything after (3) above to bullets. Refer to the template for more.

https://oracle.github.io/learning-library/sample-livelabs-templates/livelabs-template/workshops/livelabs/index.html
https://oracle.github.io/learning-library/sample-livelabs-templates/sample-workshop/workshops/livelabs/index.html

Thanks,
Rene

2021-09-18 19:07 UTC, Kuassim commented
I think my latest update is compatible with the titles and body formatting requirements.

2021-09-20 14:37 UTC, rfontcha approved these changes

2021-09-20 14:37 UTC, merged

2021-09-20 16:30 UTC, Kuassim commented
I think I have addressed these comments. Is there anything else you want me to fix?