Quarterly Review for stale labs
oracle/learning-library pull request #3769
Opened 2021-09-16 20:49 UTC by malcherm

Quarterly Review - old labs that are no longer valid labs - confirmed with lab owners that these directories will be deleted

2021-09-16 21:02 UTC, jjking2019 submitted a review, later dismissed

2021-09-17 15:48 UTC, dankingsley001 approved these changes

2021-09-20 07:08 UTC, klazarz requested changes
let's review this. i have found multiple references from workshops to the to-be-deted content

2021-09-20 11:25 UTC, malcherm commented
Only workshop and ospa-library will be removed.

2021-09-27 14:07 UTC, malcherm commented
[file_review_to_be deleted.txt](https://github.com/oracle/learning-library/files/7236840/file_review_to_be.deleted.txt)
Files found with reference to OSPA and workshop have been reviewed and are old temporary files that also needed to be purged. One reference found to old and outdated lab that is no longer used. 
No dependencies found- please merge.

2021-09-27 14:09 UTC, closed without merging