ID#8442 Move workshop to live labs
oracle/learning-library pull request #4217
Opened 2021-11-22 07:16 UTC by rrumale

ID#8442 - Full stack development using Python and deployment via OKE

2021-11-22 10:54 UTC, klazarz requested changes
Hi @rrumale , can you please ake sure that there is not URL on: [proceed to the next lab](#next).
You can leave 'proceed to the next lab' but please do not add a link as per latest self QA checklist.

2021-11-22 13:03 UTC, rrumale commented
Removed the link as suggested
"can you please ake sure that there is not URL on: proceed to the next lab.
You can leave 'proceed to the next lab' but please do not add a link as per latest self QA checklist."

2021-11-22 19:46 UTC, kamryn-v approved these changes

2021-11-23 08:42 UTC, klazarz approved these changes

2021-11-23 08:42 UTC, merged