Workshop ID 5921: GoldenGate Stream Analytics - Your HelloWorld Pipeline in 15 minutes!
oracle/learning-library pull request #4268
Opened 2021-12-03 13:10 UTC by prmanjun

Formatting and date changes.

2021-12-03 14:32 UTC, rfontcha commented on data-management-library/goldengate/stream-analytics-helloworld-pipeline/1-ggsa-hwp/1-ggsa-hwp.md
> +- An On-prem or a Marketplace instance of GoldenGate Stream Analytics (GGSA) version 19.1:
Remove this line

2021-12-03 14:32 UTC, rfontcha commented on data-management-library/goldengate/stream-analytics-helloworld-pipeline/1-ggsa-hwp/1-ggsa-hwp.md
> +
@prmanjun - Move everything from this line to the "Learn more" section

2021-12-03 14:35 UTC, rfontcha requested changes
@prmanjun - Please see my comments in-line "1-ggsa-hwp"

2021-12-07 08:48 UTC, klazarz requested changes
@prmanjun please also use desriptions for your images, see self QA doc

2021-12-09 16:33 UTC, prmanjun commented on data-management-library/goldengate/stream-analytics-helloworld-pipeline/1-ggsa-hwp/1-ggsa-hwp.md
> +- An On-prem or a Marketplace instance of GoldenGate Stream Analytics (GGSA) version 19.1:
Closed

2021-12-09 16:33 UTC, prmanjun commented on data-management-library/goldengate/stream-analytics-helloworld-pipeline/1-ggsa-hwp/1-ggsa-hwp.md
> +
Closed

2021-12-09 16:46 UTC, prmanjun commented
> @prmanjun please also use desriptions for your images, see self QA doc



> @prmanjun please also use desriptions for your images, see self QA doc

Closed

2021-12-10 08:12 UTC, klazarz approved these changes

2021-12-13 15:43 UTC, rfontcha approved these changes

2021-12-13 15:43 UTC, merged