Updated Lab - Retail Segmentation ID#7841
oracle/learning-library pull request #4333
Opened 2021-12-22 19:25 UTC by AustinChinOCI

Fixed Formatting from recommendations from Anoosha Pilli

2021-12-23 19:40 UTC, kaylien approved these changes
The workshop has been reviewed and is ready for approval

2021-12-23 20:43 UTC, kaylien requested changes
Upon further review, there needs to be a couple more changes. Underneath the steps, there are now bulletpoints for all text instead of numbers.

This file
![image](https://user-images.githubusercontent.com/20189073/147289191-204f1d57-d512-4693-b0f9-f3a03eff143a.png)

Original file
![image](https://user-images.githubusercontent.com/20189073/147289208-c9d7a3b5-30b2-42eb-a306-7bb400f3608d.png)

Only the text/images/code snippets underneath the numbered text needs to be indented 4 spaces. Here is a sample of indentation, it can be found in /learning-library/sample-livelabs-templates/livelabs-template/sample-livelabs/template.md

![image](https://user-images.githubusercontent.com/20189073/147289845-cb5ddf7c-2d1c-45e7-b4ec-b9fef335e2a8.png)

2021-12-23 21:04 UTC, AustinChinOCI commented
I have fixed formatting errors as you had mentioned, hopefully this will be good now.

2022-01-04 15:07 UTC, malcherm approved these changes

2022-01-04 15:07 UTC, merged