introducing 2 new workshops and update in 1 existing workshop
oracle/learning-library pull request #4612
Opened 2022-03-02 04:15 UTC by romitacharya

2 new workshops:

- EM patching using Fleet UI
- EM Upgrade using Fleet UI

Update in existing workshop

- EM upgrade (this change will make both command line and UI based labs in sync, with no drifters)

2022-03-02 10:35 UTC, klazarz commented
Hi @romitacharya, could you please add the WMS ID(s). Thanks, Keivn

2022-03-02 11:00 UTC, romitacharya commented
> 

Hi @klazarz , I have added it. Thanks, Romit

2022-03-03 04:18 UTC, rfontcha commented on enterprise-manageability-library/enterprise-manager/workshops/livelabs/manifest.json
> +      "title": "Lab 5A: Automated Database Patching at Scale with Fleet Maintenance UI",
Lab # are all digits. Please use sequences and not 6A/7A, etc.

2022-03-03 04:28 UTC, rfontcha requested changes
@romitacharya . Please use this for :
- "Lab 2: Environment Setup" in all Freetier manifest.json: https://raw.githubusercontent.com/oracle/learning-library/master/common/labs/setup-compute-generic/setup-compute-novnc-ssh.md
- "Lab 1: Environment Setup" in all "livelabs manifest.json: https://raw.githubusercontent.com/oracle/learning-library/master/common/labs/verify-compute/verify-compute-ssh-and-novnc.md

Also modify all Labs numbers to sequences. not 6A, 7A etc. Must be a number

2022-03-03 04:30 UTC, romitacharya commented on enterprise-manageability-library/enterprise-manager/workshops/livelabs/manifest.json
> +      "title": "Lab 5A: Automated Database Patching at Scale with Fleet Maintenance UI",
Thanks @rfontcha . I have made the necessary changes. UI workshop is not part of fundamental workshop for now, and I have removed the references from manifest.json file.

2022-03-03 05:36 UTC, romitacharya commented
> @romitacharya . Please use this for :
> 
> * "Lab 2: Environment Setup" in all Freetier manifest.json: https://raw.githubusercontent.com/oracle/learning-library/master/common/labs/setup-compute-generic/setup-compute-novnc-ssh.md
> * "Lab 1: Environment Setup" in all "livelabs manifest.json: https://raw.githubusercontent.com/oracle/learning-library/master/common/labs/verify-compute/verify-compute-ssh-and-novnc.md
> 
> Also modify all Labs numbers to sequences. not 6A, 7A etc. Must be a number

Hi @rfontcha Suggested changes done..

2022-03-03 15:35 UTC, rfontcha commented on enterprise-manageability-library/enterprise-manager/workshops/livelabs/manifest.json
> +      "title": "Lab 5A: Automated Database Patching at Scale with Fleet Maintenance UI",
@romitacharya  - Remove all "../workshop/main-*". They're no longer used. Also make sure that your repo is in sync by running "Merge into current branch" and selecting "upstream/master"

2022-03-03 17:14 UTC, rfontcha approved these changes

2022-03-03 17:14 UTC, merged