WMS ID: 1621 Oracle Analytics Server
oracle/learning-library pull request #5058
Opened 2022-05-19 14:54 UTC by ltdest

submitting modifications from OA review

2022-05-19 18:17 UTC, rfontcha requested changes
@ltdest  - Excellent work renaming the images and providing "Alt text" for all screenshots. There a few items to address: Use of underscore and mixed/uppercase 

- Replace underscore with hyphen/dash on all file names e.g. rename `analytics-library/oas-new/augmented-analytics/images/**attritionpredict_bc_nbmodelinspectoption.png**` to `analytics-library/oas-new/augmented-analytics/images/**attritionpredict-bc-nbmodelinspectoption.png**`

- Rename `analytics-library/oas-new/augmented-analytics/images/Savedataflowpanel.png` to lowercase. i.e. `analytics-library/oas-new/augmented-analytics/images/Savedataflowpanel.png`. 

When you're done, commit and push

2022-05-23 15:03 UTC, rfontcha requested changes
@ltdest - The file `analytics-library/oas-new/augmented-analytics/images/Savedataflowpanel.png` mentioned in my last comments is still not renamed. Also remove the hidden file `analytics-library/oas-new/augmented-analytics/images/.imagesplusiconandsavedataicon.png`

![image](https://user-images.githubusercontent.com/65045046/169849142-0b8fea69-740c-4354-8f0f-43ba0d1009c3.png)

2022-05-23 15:12 UTC, ltdest commented
I’ve made the change at my end. . . this is what I submitted.

I guess I can rename the file to something else in order to force the change.

***@***.***

Warm regards, Linda
[Oracle]<http://www.oracle.com/>
Linda Dest, Technology Platform Specialist
Mobile: +12032157555<tel:+12032157555>
Oracle Solution Engineering

Your feedback matters. Please share.<https://feedback.oracle.com/?salesexperience&ID=NA-CT-LW>
From: Rene Fontcha ***@***.***>
Sent: Monday, May 23, 2022 11:04 AM
To: oracle/learning-library ***@***.***>
Cc: Linda Dest ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle/learning-library] WMS ID: 1621 Oracle Analytics Server (PR #5058)


@rfontcha requested changes on this pull request.

@ltdest<https://urldefense.com/v3/__https:/github.com/ltdest__;!!ACWV5N9M2RV99hQ!PK2u6Duc9VAtotz7h_BgJKiuME4PwWHNyD_PA4shE-myJ9PEf7SOzJ0eESlxV5_QoVjY5ukpJMRUiH36mQBizTNb$> - The file analytics-library/oas-new/augmented-analytics/images/Savedataflowpanel.png mentioned in my last comments is still not renamed. Also remove the hidden file analytics-library/oas-new/augmented-analytics/images/.imagesplusiconandsavedataicon.png

[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/65045046/169849142-0b8fea69-740c-4354-8f0f-43ba0d1009c3.png__;!!ACWV5N9M2RV99hQ!PK2u6Duc9VAtotz7h_BgJKiuME4PwWHNyD_PA4shE-myJ9PEf7SOzJ0eESlxV5_QoVjY5ukpJMRUiH36meT3h680$>

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/oracle/learning-library/pull/5058*pullrequestreview-981925818__;Iw!!ACWV5N9M2RV99hQ!PK2u6Duc9VAtotz7h_BgJKiuME4PwWHNyD_PA4shE-myJ9PEf7SOzJ0eESlxV5_QoVjY5ukpJMRUiH36mQfWBBTv$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/AXIKIUQPXWJDF3HOPC4IU3DVLOM4NANCNFSM5WMQK2SA__;!!ACWV5N9M2RV99hQ!PK2u6Duc9VAtotz7h_BgJKiuME4PwWHNyD_PA4shE-myJ9PEf7SOzJ0eESlxV5_QoVjY5ukpJMRUiH36mUV02fu9$>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2022-05-23 16:39 UTC, rfontcha approved these changes

2022-05-23 16:39 UTC, merged