Clarify "Always Free"
oracle/learning-library pull request #5113
Opened 2022-06-06 12:24 UTC by nigelbayliss

Make "Always Free" clearer

2022-06-06 16:42 UTC, arabellayao requested changes
Please include the WMS ID for the workshop in the title of your pull request. Thank you!

2022-06-06 16:47 UTC, nigelbayliss commented
ID 9061

2022-06-06 19:08 UTC, arabellayao approved these changes

2022-06-07 03:28 UTC, madhusudhanrao-ppm approved these changes

2022-06-07 03:28 UTC, merged