In this Livelab, Anyone can learn how to migrate SSAS DB's from On-Pr…
oracle/learning-library pull request #5133
Opened 2022-06-13 16:39 UTC by devinderpalsingh

…emise to OCI (Compute Instance)

Live Lab : "migrating-ssas-db-to-oci" created successfully.

Live Lab Name: Migrating Microsoft SQL Server Analysis Service (SSAS) Databases to OCI

Co-Authored-By: ramdonti <102347914+ramdonti@users.noreply.github.com>

2022-06-13 18:32 UTC, arabellayao requested changes
Hi! Please include the workshop's WMS ID in the title of your pull request. Thank you!

2022-06-14 07:16 UTC, madhusudhanrao-ppm commented
Please give a self-descriptive image name and refer QA checklist document for naming conventions also images should have alt text from an accessibility perspective

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/70625227/173516311-a887514e-3532-4f51-9e38-9b048cd88246.png">

2022-06-14 12:11 UTC, devinderpalsingh commented
We have given self-descriptive image name by referring QA Checklist. Could you please let us know if we are good now or anything else needed from our side.

WMS ID: 11044

2022-06-14 21:44 UTC, malcherm approved these changes

2022-06-14 21:44 UTC, merged